### ISSUE TITLE
YOU'RE SO STUPID AND CONTAGIOUS

### ISSUE THREAD

**Issue by ghost** [PoleyMagik/GoTools#1]
YOU'RE SO STUPID AND CONTAGIOUS

**Comment by ghost** [comment]
also, this is sam after being groomed by benson

**Comment by ghost** [comment]
this will make you understand the basics
![GVcSoz-XYAAiKeA](https://github.com/user-attachments/assets/2e034e79-6316-4d6c-861d-ffa2813d0a3d)

**Comment by ghost** [comment]
do you know this?
![IMG_20240921_222613629_HDR](https://github.com/user-attachments/assets/015d6bfd-eb2c-4bea-8152-b2a914e59361)
![IMG_20240921_222736857_HDR](https://github.com/user-attachments/assets/06db9bd1-0b9a-47b6-abc0-e5d117ad4314)
![IMG_20240921_222755653_HDR](https://github.com/user-attachments/assets/3d883b65-e25a-4e6a-a68d-2439f7d580b8)
![IMG_20240921_222811359_HDR](https://github.com/user-attachments/assets/e7063da8-614f-4a45-93f1-b4967afae8f3)
![IMG_20240921_222823686_HDR](https://github.com/user-attachments/assets/c3c8ca6a-f56e-4198-92e2-408bc49d1f7d)

**Comment by ghost** [comment]
you know what, just pretend this account was never here to begin with, i feel like shit and insecure for what i truly believe

**Comment by ItsJayPM** [comment]
Hey man, it's okay, we all go through eras we know in retrospect aren't great. I for sure regret what I've done on the internet. By recognizing the problem, you've already taken the first step. I don't know who you are because you deleted your account, but I do surely hope you find a better life that doesn't involve shaming minorities and 16 year olds who you really don't know. If you want to talk, you can join the FlashThemes server and from there dm me, I know you came at me with pretty harsh anti-trans rhetoric but I believe people can change from that. You have the potential to be great, everybody does :)

**Comment by LoganCabrera** [comment]
alright, here i am on my main. why would i ever want to talk to you when you'll just ban me? i don't think you really give a shit about me nor what i have to offer, despite the laziness and procrastination i have trouble overcoming currently.

**Comment by LoganCabrera** [comment]
alright, here i am on my main. why would i ever want to talk to you when you'll just ban me? i don't think you really give a shit about me nor what i have to offer, despite the laziness and procrastination i have trouble overcoming currently. besides, i was banned from goanimate city and wrapper: offline i don't trust this but i'll take the risk because fuck it.
